// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: quotes/v1/quotes.proto

package quotesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuotesService_UpdateQuote_FullMethodName    = "/quotes.v1.QuotesService/UpdateQuote"
	QuotesService_GetQuoteUpdate_FullMethodName = "/quotes.v1.QuotesService/GetQuoteUpdate"
	QuotesService_GetLatestQuote_FullMethodName = "/quotes.v1.QuotesService/GetLatestQuote"
)

// QuotesServiceClient is the client API for QuotesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QuotesService — асинхронный сервис котировок валютных пар.
type QuotesServiceClient interface {
	// Creates a quote update job. The optional Idempotency-Key HTTP header
	// makes repeated requests return the original job.
	UpdateQuote(ctx context.Context, in *UpdateQuoteRequest, opts ...grpc.CallOption) (*UpdateQuoteResponse, error)
	// Возвращает статус/результат конкретной задачи обновления.
	GetQuoteUpdate(ctx context.Context, in *GetQuoteUpdateRequest, opts ...grpc.CallOption) (*GetQuoteUpdateResponse, error)
	// Возвращает последнее известное значение котировки пары.
	GetLatestQuote(ctx context.Context, in *GetLatestQuoteRequest, opts ...grpc.CallOption) (*GetLatestQuoteResponse, error)
}

type quotesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotesServiceClient(cc grpc.ClientConnInterface) QuotesServiceClient {
	return &quotesServiceClient{cc}
}

func (c *quotesServiceClient) UpdateQuote(ctx context.Context, in *UpdateQuoteRequest, opts ...grpc.CallOption) (*UpdateQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateQuoteResponse)
	err := c.cc.Invoke(ctx, QuotesService_UpdateQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotesServiceClient) GetQuoteUpdate(ctx context.Context, in *GetQuoteUpdateRequest, opts ...grpc.CallOption) (*GetQuoteUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuoteUpdateResponse)
	err := c.cc.Invoke(ctx, QuotesService_GetQuoteUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotesServiceClient) GetLatestQuote(ctx context.Context, in *GetLatestQuoteRequest, opts ...grpc.CallOption) (*GetLatestQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestQuoteResponse)
	err := c.cc.Invoke(ctx, QuotesService_GetLatestQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuotesServiceServer is the server API for QuotesService service.
// All implementations must embed UnimplementedQuotesServiceServer
// for forward compatibility.
//
// QuotesService — асинхронный сервис котировок валютных пар.
type QuotesServiceServer interface {
	// Creates a quote update job. The optional Idempotency-Key HTTP header
	// makes repeated requests return the original job.
	UpdateQuote(context.Context, *UpdateQuoteRequest) (*UpdateQuoteResponse, error)
	// Возвращает статус/результат конкретной задачи обновления.
	GetQuoteUpdate(context.Context, *GetQuoteUpdateRequest) (*GetQuoteUpdateResponse, error)
	// Возвращает последнее известное значение котировки пары.
	GetLatestQuote(context.Context, *GetLatestQuoteRequest) (*GetLatestQuoteResponse, error)
	mustEmbedUnimplementedQuotesServiceServer()
}

// UnimplementedQuotesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuotesServiceServer struct{}

func (UnimplementedQuotesServiceServer) UpdateQuote(context.Context, *UpdateQuoteRequest) (*UpdateQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQuote not implemented")
}
func (UnimplementedQuotesServiceServer) GetQuoteUpdate(context.Context, *GetQuoteUpdateRequest) (*GetQuoteUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuoteUpdate not implemented")
}
func (UnimplementedQuotesServiceServer) GetLatestQuote(context.Context, *GetLatestQuoteRequest) (*GetLatestQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestQuote not implemented")
}
func (UnimplementedQuotesServiceServer) mustEmbedUnimplementedQuotesServiceServer() {}
func (UnimplementedQuotesServiceServer) testEmbeddedByValue()                       {}

// UnsafeQuotesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuotesServiceServer will
// result in compilation errors.
type UnsafeQuotesServiceServer interface {
	mustEmbedUnimplementedQuotesServiceServer()
}

func RegisterQuotesServiceServer(s grpc.ServiceRegistrar, srv QuotesServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuotesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuotesService_ServiceDesc, srv)
}

func _QuotesService_UpdateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotesServiceServer).UpdateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotesService_UpdateQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotesServiceServer).UpdateQuote(ctx, req.(*UpdateQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotesService_GetQuoteUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotesServiceServer).GetQuoteUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotesService_GetQuoteUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotesServiceServer).GetQuoteUpdate(ctx, req.(*GetQuoteUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotesService_GetLatestQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotesServiceServer).GetLatestQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotesService_GetLatestQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotesServiceServer).GetLatestQuote(ctx, req.(*GetLatestQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuotesService_ServiceDesc is the grpc.ServiceDesc for QuotesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuotesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quotes.v1.QuotesService",
	HandlerType: (*QuotesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateQuote",
			Handler:    _QuotesService_UpdateQuote_Handler,
		},
		{
			MethodName: "GetQuoteUpdate",
			Handler:    _QuotesService_GetQuoteUpdate_Handler,
		},
		{
			MethodName: "GetLatestQuote",
			Handler:    _QuotesService_GetLatestQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quotes/v1/quotes.proto",
}
