// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: quotes/v1/quotes.proto

package quotesv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_PROCESSING  JobStatus = 2
	JobStatus_JOB_STATUS_DONE        JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_PROCESSING",
		3: "JOB_STATUS_DONE",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_PROCESSING":  2,
		"JOB_STATUS_DONE":        3,
		"JOB_STATUS_FAILED":      4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_quotes_v1_quotes_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_quotes_v1_quotes_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_quotes_v1_quotes_proto_rawDescGZIP(), []int{0}
}

type UpdateQuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Код пары в формате "BASE/QUOTE", например "EUR/MXN".
	Pair          string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteRequest) Reset() {
	*x = UpdateQuoteRequest{}
	mi := &file_quotes_v1_quotes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteRequest) ProtoMessage() {}

func (x *UpdateQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v1_quotes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quotes_v1_quotes_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateQuoteRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type UpdateQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=quotes.v1.JobStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteResponse) Reset() {
	*x = UpdateQuoteResponse{}
	mi := &file_quotes_v1_quotes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteResponse) ProtoMessage() {}

func (x *UpdateQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v1_quotes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuoteResponse) Descriptor() ([]byte, []int) {
	return file_quotes_v1_quotes_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateQuoteResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateQuoteResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

type GetQuoteUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteUpdateRequest) Reset() {
	*x = GetQuoteUpdateRequest{}
	mi := &file_quotes_v1_quotes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteUpdateRequest) ProtoMessage() {}

func (x *GetQuoteUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v1_quotes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteUpdateRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteUpdateRequest) Descriptor() ([]byte, []int) {
	return file_quotes_v1_quotes_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuoteUpdateRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetQuoteUpdateResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	JobId     string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Pair      string                 `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Status    JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=quotes.v1.JobStatus" json:"status,omitempty"`
	Price     *string                `protobuf:"bytes,4,opt,name=price,proto3,oneof" json:"price,omitempty"` // Decimal string; present only for JOB_STATUS_DONE.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Public failure reason; present only for JOB_STATUS_FAILED.
	ErrorMessage  *string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteUpdateResponse) Reset() {
	*x = GetQuoteUpdateResponse{}
	mi := &file_quotes_v1_quotes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteUpdateResponse) ProtoMessage() {}

func (x *GetQuoteUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v1_quotes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteUpdateResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteUpdateResponse) Descriptor() ([]byte, []int) {
	return file_quotes_v1_quotes_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuoteUpdateResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetQuoteUpdateResponse) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *GetQuoteUpdateResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *GetQuoteUpdateResponse) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *GetQuoteUpdateResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetQuoteUpdateResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type GetLatestQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestQuoteRequest) Reset() {
	*x = GetLatestQuoteRequest{}
	mi := &file_quotes_v1_quotes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestQuoteRequest) ProtoMessage() {}

func (x *GetLatestQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v1_quotes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetLatestQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quotes_v1_quotes_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestQuoteRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type GetLatestQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestQuoteResponse) Reset() {
	*x = GetLatestQuoteResponse{}
	mi := &file_quotes_v1_quotes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestQuoteResponse) ProtoMessage() {}

func (x *GetLatestQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quotes_v1_quotes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetLatestQuoteResponse) Descriptor() ([]byte, []int) {
	return file_quotes_v1_quotes_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestQuoteResponse) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *GetLatestQuoteResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetLatestQuoteResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_quotes_v1_quotes_proto protoreflect.FileDescriptor

const file_quotes_v1_quotes_proto_rawDesc = "" +
	"\n" +
	"\x16quotes/v1/quotes.proto\x12\tquotes.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\x12UpdateQuoteRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\"Z\n" +
	"\x13UpdateQuoteResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.quotes.v1.JobStatusR\x06status\".\n" +
	"\x15GetQuoteUpdateRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x8d\x02\n" +
	"\x16GetQuoteUpdateResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04pair\x18\x02 \x01(\tR\x04pair\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.quotes.v1.JobStatusR\x06status\x12\x19\n" +
	"\x05price\x18\x04 \x01(\tH\x00R\x05price\x88\x01\x01\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12(\n" +
	"\rerror_message\x18\x06 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\b\n" +
	"\x06_priceB\x10\n" +
	"\x0e_error_message\"+\n" +
	"\x15GetLatestQuoteRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\"}\n" +
	"\x16GetLatestQuoteResponse\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x86\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15JOB_STATUS_PROCESSING\x10\x02\x12\x13\n" +
	"\x0fJOB_STATUS_DONE\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x042\xe8\x02\n" +
	"\rQuotesService\x12j\n" +
	"\vUpdateQuote\x12\x1d.quotes.v1.UpdateQuoteRequest\x1a\x1e.quotes.v1.UpdateQuoteResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/quote-updates\x12y\n" +
	"\x0eGetQuoteUpdate\x12 .quotes.v1.GetQuoteUpdateRequest\x1a!.quotes.v1.GetQuoteUpdateResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/quote-updates/{job_id}\x12p\n" +
	"\x0eGetLatestQuote\x12 .quotes.v1.GetLatestQuoteRequest\x1a!.quotes.v1.GetLatestQuoteResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/quotes/latestB3Z1currency-quotes/internal/genpb/quotes/v1;quotesv1b\x06proto3"

var (
	file_quotes_v1_quotes_proto_rawDescOnce sync.Once
	file_quotes_v1_quotes_proto_rawDescData []byte
)

func file_quotes_v1_quotes_proto_rawDescGZIP() []byte {
	file_quotes_v1_quotes_proto_rawDescOnce.Do(func() {
		file_quotes_v1_quotes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quotes_v1_quotes_proto_rawDesc), len(file_quotes_v1_quotes_proto_rawDesc)))
	})
	return file_quotes_v1_quotes_proto_rawDescData
}

var file_quotes_v1_quotes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_quotes_v1_quotes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_quotes_v1_quotes_proto_goTypes = []any{
	(JobStatus)(0),                 // 0: quotes.v1.JobStatus
	(*UpdateQuoteRequest)(nil),     // 1: quotes.v1.UpdateQuoteRequest
	(*UpdateQuoteResponse)(nil),    // 2: quotes.v1.UpdateQuoteResponse
	(*GetQuoteUpdateRequest)(nil),  // 3: quotes.v1.GetQuoteUpdateRequest
	(*GetQuoteUpdateResponse)(nil), // 4: quotes.v1.GetQuoteUpdateResponse
	(*GetLatestQuoteRequest)(nil),  // 5: quotes.v1.GetLatestQuoteRequest
	(*GetLatestQuoteResponse)(nil), // 6: quotes.v1.GetLatestQuoteResponse
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_quotes_v1_quotes_proto_depIdxs = []int32{
	0, // 0: quotes.v1.UpdateQuoteResponse.status:type_name -> quotes.v1.JobStatus
	0, // 1: quotes.v1.GetQuoteUpdateResponse.status:type_name -> quotes.v1.JobStatus
	7, // 2: quotes.v1.GetQuoteUpdateResponse.updated_at:type_name -> google.protobuf.Timestamp
	7, // 3: quotes.v1.GetLatestQuoteResponse.updated_at:type_name -> google.protobuf.Timestamp
	1, // 4: quotes.v1.QuotesService.UpdateQuote:input_type -> quotes.v1.UpdateQuoteRequest
	3, // 5: quotes.v1.QuotesService.GetQuoteUpdate:input_type -> quotes.v1.GetQuoteUpdateRequest
	5, // 6: quotes.v1.QuotesService.GetLatestQuote:input_type -> quotes.v1.GetLatestQuoteRequest
	2, // 7: quotes.v1.QuotesService.UpdateQuote:output_type -> quotes.v1.UpdateQuoteResponse
	4, // 8: quotes.v1.QuotesService.GetQuoteUpdate:output_type -> quotes.v1.GetQuoteUpdateResponse
	6, // 9: quotes.v1.QuotesService.GetLatestQuote:output_type -> quotes.v1.GetLatestQuoteResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_quotes_v1_quotes_proto_init() }
func file_quotes_v1_quotes_proto_init() {
	if File_quotes_v1_quotes_proto != nil {
		return
	}
	file_quotes_v1_quotes_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quotes_v1_quotes_proto_rawDesc), len(file_quotes_v1_quotes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quotes_v1_quotes_proto_goTypes,
		DependencyIndexes: file_quotes_v1_quotes_proto_depIdxs,
		EnumInfos:         file_quotes_v1_quotes_proto_enumTypes,
		MessageInfos:      file_quotes_v1_quotes_proto_msgTypes,
	}.Build()
	File_quotes_v1_quotes_proto = out.File
	file_quotes_v1_quotes_proto_goTypes = nil
	file_quotes_v1_quotes_proto_depIdxs = nil
}
